def show_menu():
    print("════════════════════════════")
    print("🤖 AI LEARNING MENTOR")
    print("Powered by Google Gemini AI")
    print("════════════════════════════")
    print()
    print("🎓 STUDENT")
    print("1. Enter Student Details")
    print()
    print("🚀 AI FEATURES")
    print("2. Generate Career Roadmap")
    print("3. Recommend Learning Resources")
    print("4. Suggest AI Projects")
    print("5. Generate Complete Report")
    print()
    print("💾 FILE")
    print("6. Save Report")
    print()
    print("🚪 EXIT")
    print("7. Exit")

    print(" ENTER 1: FOR STUDENT DETAIL ")

    return input("\nEnter your choice: ")